version: '3.7'

services:
  api:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - app:/home/app/web/app
      - migrations:/home/app/web/migrations
    restart: always

  db:
    env_file:
      - ./.env.dev
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  app:
  migrations:


