version: '3.7'

services:
  api:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    env_file:
      - ./.env.dev
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


