"""empty message

Revision ID: 9cb8ae636e33
Revises: 90e64856adc4
Create Date: 2020-07-22 12:03:03.199102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb8ae636e33'
down_revision = '90e64856adc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
